### ISSUE TITLE
Create a graphical configuration editor

### ISSUE THREAD

**Issue by Conr86** [SFXRescue/SARTInterface#12]
At the moment, configuration editing is done through a YAML based editor window, which provides advanced control, but at the cost of usability.

At some point, a proper graphical editor should be implemented, but not until the exact contents of the configuration file are unlikely to change.

**Comment by WilliamsJack** [comment]
The config editor could also be generated by the interface depending on the contents.

However, that does mean that if a option is not present in the file, it won't be generated.

Perhaps it would be prudent to have both "visual" and "text" tabs, reminiscent of "Fancy Pants Editor" and "Markdown" tabs on Reddit. Fancy pants can be generated by the config file, and the text editor would allow adding new fields.

**Comment by WilliamsJack** [comment]
Parsing a JSON schema to generate valid config options with descriptions and default values could be a good way to implement this. Since the schema is standard we could also use it to allow the user to create new configs from right within the interface.
I'll do some preliminary development tonight after work. Stay tuned.

**Comment by WilliamsJack** [comment]
Thanks!

(Also testing GitHub bot)
